const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const outPath = path.resolve(__dirname, '..', 'Bibliography.pdf');
const doc = new PDFDocument({ margin: 50, size: 'A4' });
const stream = fs.createWriteStream(outPath);
doc.pipe(stream);

function title(text) {
  doc.font('Helvetica-Bold').fontSize(18).text(text, {align: 'center'});
  doc.moveDown(0.5);
}

function heading(text) {
  doc.font('Helvetica-Bold').fontSize(12).text(text);
  doc.moveDown(0.2);
}

function entry(text) {
  doc.font('Helvetica').fontSize(11).text(text, {align: 'left'});
  doc.moveDown(0.2);
}

// Metadata
doc.info.Title = 'Bibliography - Heritage Recipes Lite';
doc.info.Author = 'Paramveer Gupta';

// Title
title('Bibliography');
doc.moveDown(0.2);

heading('Project: Heritage Recipes Lite');
entry('Author: Paramveer Gupta');
entry('Date: 2025-11-17');

doc.moveDown(0.5);
heading('References');

const refs = [
  {
    cite: 'Flutter Documentation',
    details: 'Google. Flutter documentation: https://flutter.dev/docs (accessed 2025)'
  },
  {
    cite: 'Dart Language',
    details: 'Dart language tour: https://dart.dev (accessed 2025)'
  },
  {
    cite: 'Node.js',
    details: 'Node.js Documentation: https://nodejs.org/en/docs/ (accessed 2025)'
  },
  {
    cite: 'Express.js',
    details: 'Express - Node.js web framework: https://expressjs.com/ (accessed 2025)'
  },
  {
    cite: 'MongoDB',
    details: 'MongoDB Manual: https://www.mongodb.com/docs/ (accessed 2025)'
  },
  {
    cite: 'Mongoose',
    details: 'Mongoose ODM Documentation: https://mongoosejs.com/docs/guide.html (accessed 2025)'
  },
  {
    cite: 'JSON Web Tokens',
    details: 'JWT introduction: https://jwt.io/introduction/ (accessed 2025)'
  },
  {
    cite: 'bcryptjs',
    details: 'bcryptjs npm package: https://www.npmjs.com/package/bcryptjs (accessed 2025)'
  },
  {
    cite: 'PDFKit',
    details: 'PDFKit Documentation: https://pdfkit.org/ (accessed 2025)'
  },
  {
    cite: 'REST Architectural Style',
    details: 'Fielding, R. T. (2000). Architectural Styles and the Design of Network-based Software Architectures. PhD dissertation, University of California, Irvine. https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm (accessed 2025)'
  },
  {
    cite: 'HTTP/1.1',
    details: 'Hypertext Transfer Protocol -- HTTP/1.1. RFC 7231. https://tools.ietf.org/html/rfc7231 (accessed 2025)'
  },
  {
    cite: 'Git & GitHub',
    details: 'Git documentation and GitHub for source control: https://git-scm.com/ and https://github.com/ (accessed 2025)'
  },
  {
    cite: 'Stack Overflow (for debugging and community help)',
    details: 'Stack Overflow: https://stackoverflow.com/ (accessed 2025)'
  },
  {
    cite: 'IB Computer Science Guide',
    details: 'International Baccalaureate. Computer Science Guide. (Use institution-provided edition and year as required). (accessed 2025)'
  }
];

refs.forEach((r, idx) => {
  entry(`${idx + 1}. ${r.cite}`);
  doc.font('Helvetica-Oblique').fontSize(10).text(`${r.details}`);
  doc.moveDown(0.4);
  doc.font('Helvetica').fontSize(11);
});

// Footer

doc.moveDown(1);
doc.font('Helvetica').fontSize(10).text('Generated by project tooling. Ensure you verify citations and adapt referencing style required by your institution.', {align: 'left'});

doc.end();

stream.on('finish', () => {
  console.log('Bibliography PDF generated at:', outPath);
});

stream.on('error', (err) => {
  console.error('Error writing Bibliography PDF:', err);
});
